const librarydata = [
  {
    id: 1,
    pc: "top-1.png",
    head: "FOUR STEPS TO A SUPER SAFE ACCOUNT",
    one: "User Saftey",
    two: "Privacy",
    category: "Platform Integrity",
  },
  {
    id: 2,
    pc: "top-2.png",
    head: "TIPS AGAINST SPAM AND HACKING",
    one: "Account Security",
    two: "User Saftey",
    category: "Platform Integrity",
  },
  {
    id: 3,
    pc: "top-3.svg",
    head: "AGE-RESTRICTED CONTENT ON DISCORD",
    one: "Server Saftey",
    two: "User Saftey",
    category: "Platform Integrity",
  },
  {
    id: 4,
    pc: "top-4.svg",
    head: "DISCORD'S COMMITMENT TO A SAFE AND TRUSTED EXPERIENCE",
    one: "Parents ans Teens",
    two: "Privacy",
    category: "Platform Integrity",
  },
  {
    id: 5,
    pc: "top-5.svg",
    head: "TALKING ABOUT ONLINE SAFETY WITH YOUR TEEN",
    one: "Policy",
    two: "Server Saftey",
    category: "Account Security",
  },
  {
    id: 6,
    pc: "top-6.png",
    head: "HELPING YOUR TEEN STAY SAFE ON DISCORD",
    one: "Reporting",
    two: "User Saftey",
    category: "Account Security",
  },
  {
    id: 7,
    pc: "top-7.png",
    head: "ROLE OF ADMINISTRATORS AND MODERATORS ON DISCORD",
    one: "Account SEcurity",
    two: "User Saftey",
    category: "Account Security",
  },
  {
    id: 8,
    pc: "top-8.png",
    head: "ANSWERING PARENTS' AND EDUCATORS' TOP QUESTIONS",
    one: "User Saftey",
    two: "Policy",
    category: "Moderation",
  },
  {
    id: 9,
    pc: "top-9.svg",
    head: "IF YOUR TEEN ENCOUNTERS AN ISSUE",
    one: "Policy",
    two: "User Saftey",
    category: "Moderation",
  },
  {
    id: 10,
    pc: "top-10.png",
    head: "HOW YOU CAN APPEAL OUR ACTIONS",
    one: "Policy",
    two: "Account Security",
    category: "Moderation",
  },
  {
    id: 11,
    pc: "top-11.svg",
    head: "MENTAL HEALTH ON DISCORD",
    one: "Account Security",
    two: "User Saftey",
    category: "Moderation",
  },
  {
    id: 12,
    pc: "top-12.png",
    head: "REPORTING ABUSIVE BEHAVIOR TO DISCORD",
    one: "Account Security",
    two: "Modaration",
    category: "Partnarship",
  },
  {
    id: 13,
    pc: "top-13.png",
    head: "WHAT IS DISCORD?",
    one: "Modaration",
    two: "User Saftey",
    category: "Partnarship",
  },
  {
    id: 14,
    pc: "top-14.png",
    head: "PROTECTING AGAINST SCAMS ON DISCORD",
    one: "User Saftey",
    two: "Account Security",
    category: "Policy",
  },
  {
    id: 15,
    pc: "top-1.png",
    head: "HOW TRUST-SAFETY ADDRESSES VIOLENT EXTREMISM ON DISCORD",
    one: "Account Security",
    two: "User Saftey",
    category: "Policy",
  },
  {
    id: 16,
    pc: "top-1.png",
    head: "INTERNAL CONFLICT RESOLUTION",
    one: "Policy",
    two: "Account Security",
    category: "Privacy",
  },
  {
    id: 17,
    pc: "top-2.png",
    head: "USING WEBHOOKS AND EMBEDS",
    one: "Account Security",
    two: "User Saftey",
    category: "Privacy",
  },
  {
    id: 18,
    pc: "top-3.svg",
    head: "AUTO MODERATION IN DISCORD",
    one: "User Saftey",
    two: "Server Saftey",
    category: "Reporting",
  },
  {
    id: 19,
    pc: "top-7.png",
    head: "TRANSPARENCY IN MODERATION",
    one: "Account Security",
    two: "Server Saftey",
    category: "Transperency",
  },
  {
    id: 20,
    pc: "top-12.png",
    head: "PARASOCIAL RELATIONSHIPS",
    one: "Server Saftey",
    two: "Account Security",
    category: "Transperency",
  },
  {
    id: 21,
    pc: "top-13.png",
    head: "SECURING YOUR DISCORD ACCOUNT",
    one: "Modaration",
    two: "Account Security",
    category: "User saftey",
  },
  {
    id: 22,
    pc: "top-14.png",
    head: "THE APPLICATION OF METAPHORS IN MODERATION",
    one: "Account Security",
    two: "Policy",
    category: "User saftey",
  },
];
export default librarydata;
